<keyword> ::== "char" | "int" | "int16" | "int32" | "int64" | "float" | "double" | "void" | "var"
             | "fun" | "class" | "private" | "protected" | "public" | "extends" | "implements" 
             | "const" | "volatile" | "if" | "else" | "switch" | "case" | "default" | "while" 
             | "for" | "foreach" | "in" | "break" | "goto"

<ident> ::== [a-zA-Z_]{\w}*

<integer_constant> ::== {\d}+

<character_constant> ::== "\'" [\x20-\x7e] "\'"

<string> ::== "\"" {.}* "\""

